SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE ml_profit_forecast;
TRUNCATE TABLE ml_store_month_features;
TRUNCATE TABLE payroll_history;
TRUNCATE TABLE payroll_run;
TRUNCATE TABLE payroll_setting;
TRUNCATE TABLE employee_shift;
TRUNCATE TABLE employee_assignment;
TRUNCATE TABLE employee;
TRUNCATE TABLE store_neighbor;
TRUNCATE TABLE store_trade_area;
TRUNCATE TABLE sales_line_item;
TRUNCATE TABLE sales_transaction;
TRUNCATE TABLE sales_menu_daily_summary;
TRUNCATE TABLE sales_daily_summary;
TRUNCATE TABLE recipe_ingredient;
TRUNCATE TABLE purchase_history;
TRUNCATE TABLE inventory_snapshot;
TRUNCATE TABLE inventory;
TRUNCATE TABLE menu_item;
TRUNCATE TABLE store_gps;
TRUNCATE TABLE store;
TRUNCATE TABLE business_number;
TRUNCATE TABLE owner;
SET FOREIGN_KEY_CHECKS=1;
